#include "network_management.h"
#include <sys/stat.h>

#define HEADER                                                                 \
    "# This file is generated by altronix atx-sys program.\n"                  \
    "# This file will be overwritten on startup.\n"                            \
    "# To configure the network please consult atx-sys.\n\n"

#define COMMON                                                                 \
    "auto lo\n"                                                                \
    "iface lo inet loopback\n\n"

#define STATIC                                                                 \
    "auto eth0\n"                                                              \
    "iface eth0 inet static\n"                                                 \
    "  address %.*s\n"                                                         \
    "  netmask %.*s\n"                                                         \
    "  gateway %.*s\n"                                                         \
    "  pre-up /etc/network/nfs_check\n"                                        \
    "  wait-delay 15\n"                                                        \
    "  hostname %.*s\n"

#define DHCP                                                                   \
    "auto eth0\n"                                                              \
    "iface eth0 inet dhcp\n"                                                   \
    "  pre-up /etc/network/nfs_check\n"                                        \
    "  wait-delay 15\n"                                                        \
    "  hostname %.*s\n"

typedef struct tag_s
{
    jsmn_value** value;
    const char* key;
} tag_s;

int
print_network_interface(
    FILE* f,
    jsmn_value* meth,
    jsmn_value* ip,
    jsmn_value* sn,
    jsmn_value* gw,
    jsmn_value* hostname)
{
    int err;
    if (!strncmp(meth->p, "DHCP", meth->len) ||
        !strncmp(meth->p, "dhcp", meth->len) ||
        !strncmp(meth->p, "Dhcp", meth->len)) {
        err = fprintf(f, HEADER COMMON DHCP, hostname->len, hostname->p);
    } else {
        // clang-format off
        err = fprintf(
            f,
            HEADER COMMON STATIC,
            ip->len,       ip->p,
            sn->len,       sn->p,
            gw->len,       gw->p,
            hostname->len, hostname->p);
        // clang-format on
    }
    return err;
}

int
parse_network_interface(
    const char* buff,
    uint32_t len,
    jsmn_value* meth,
    jsmn_value* ip,
    jsmn_value* sn,
    jsmn_value* gw,
    jsmn_value* hostname)
{
    tag_s tags[] = { { .key = ".network.ip", .value = &ip },
                     { .key = ".network.sn", .value = &sn },
                     { .key = ".network.gw", .value = &gw },
                     { .key = ".network.meth", .value = &meth },
                     { .key = ".network.hostname", .value = &hostname } };
    int err, i, n = sizeof(tags) / sizeof(tag_s);
    struct stat st;
    jsmn_parser p;
    jsmntok_t toks[128];
    const jsmntok_t* t;

    // Parse contents
    jsmn_init(&p);
    err = jsmn_parse(&p, buff, len, toks, 128);
    if (err <= 0) { return -1; }

    for (i = 0; i < n; i++) {
        t = json_delve(buff, toks, tags[i].key);
        if (!t) break;
        (*tags[i].value)->p = &buff[t->start];
        (*tags[i].value)->len = t->end - t->start;
    }

    return i == n ? 0 : -1;
}
