#include "print_network_interface.h"

#define HEADER                                                                 \
    "# This file is generated by altronix atx-sys program.\n"                  \
    "# This file will be overwritten on startup.\n"                            \
    "# To configure the network please consult atx-sys.\n\n"

#define COMMON                                                                 \
    "auto lo\n"                                                                \
    "iface lo inet loopback\n\n"

#define STATIC                                                                 \
    "auto eth0\n"                                                              \
    "iface eth0 inet static\n"                                                 \
    "  address %s\n"                                                           \
    "  netmask %s\n"                                                           \
    "  gateway %s\n"                                                           \
    "  pre-up /etc/network/nfs_check\n"                                        \
    "  wait-delay 15\n"                                                        \
    "  hostname %s\n"

#define DHCP                                                                   \
    "auto eth0\n"                                                              \
    "iface eth0 inet dhcp\n"                                                   \
    "  pre-up /etc/network/nfs_check\n"                                        \
    "  wait-delay 15\n"                                                        \
    "  hostname %s\n"

int
print_network_interface(
    FILE* f,
    const char* meth,
    const char* ip,
    const char* sn,
    const char* gw,
    const char* hostname)
{
    int err;
    if (!strcmp(meth, "DHCP") || !strcmp(meth, "dhcp") ||
        !strcmp(meth, "Dhcp")) {
        err = fprintf(f, HEADER COMMON DHCP, hostname);
    } else {
        err = fprintf(f, HEADER COMMON STATIC, ip, sn, gw, hostname);
    }
    return err;
}
