#include "print_network_interface.h"

#define FORMAT_HEADER                                                          \
    "# This file is generated by altronix atx-sys program.\n"                  \
    "# This file will be overwritten on startup.\n"                            \
    "# To configure the network please consult atx-sys.\n\n"

#define FORMAT_COMMON                                                          \
    "auto lo\n"                                                                \
    "iface lo inet loopback\n\n"

#define FORMAT_STATIC                                                          \
    "auto eth0\n"                                                              \
    "iface eth0 inet static\n"                                                 \
    "  address %s\n"                                                           \
    "  netmask %s\n"                                                           \
    "  gateway %s\n"                                                           \
    "  pre-up /etc/network/nfs_check\n"                                        \
    "  wait-delay 15\n"                                                        \
    "  hostname %s\n"

#define FORMAT_DHCP                                                            \
    "auto eth0\n"                                                              \
    "iface eth0 inet dhcp\n"                                                   \
    "  pre-up /etc/network/nfs_check\n"                                        \
    "  wait-delay 15\n"                                                        \
    "  hostname %s\n"

int
print_network_interface(
    char* buffer,
    uint32_t* buffersz,
    const char* meth,
    const char* ip,
    const char* sn,
    const char* gw,
    const char* hostname)
{
    uint32_t max = *buffersz;
    if (!strcmp(meth, "DHCP") || !strcmp(meth, "dhcp") ||
        !strcmp(meth, "Dhcp")) {
        *buffersz = snprintf(
            buffer,
            *buffersz,
            FORMAT_HEADER FORMAT_COMMON FORMAT_DHCP,
            hostname);
    } else {
        *buffersz = snprintf(
            buffer,
            *buffersz,
            FORMAT_HEADER FORMAT_COMMON FORMAT_STATIC,
            ip,
            sn,
            gw,
            hostname);
    }
    return *buffersz < max ? 0 : -1;
}
